# -*- coding: utf-8 -*-
"""A090D116_1005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rsPHciC68mkHtCix-nbExTiq-DVD9svY

# HASH 雜湊函數 
林昱斌

1005
- md5
- sha1



- linux指令
- md5sum
- Colab使用方式 : !md5sum 檔案名稱
"""

!md5sum --help

!echo IamhappyTainan人 > 1005.txt

!cat 1005.txt

!md5sum 1005.txt

!echo iamhappyTainan人 > 1005a.txt

!cat 1005a.txt

!md5sum 1005a.txt